# Generated by Django 3.0.3 on 2020-03-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_airline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Airoport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_airoport', models.CharField(max_length=200)),
                ('latitude', models.IntegerField()),
                ('timezone1', models.IntegerField()),
                ('timezone2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plane', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clé_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Airline')),
                ('clé_airoport', models.ManyToManyField(blank=True, related_name='clé_route', to='blogs.Airoport')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50)),
                ('clé_contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry')),
            ],
        ),
        migrations.AddField(
            model_name='airoport',
            name='clé_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.City'),
        ),
        migrations.AddField(
            model_name='airline',
            name='clé_contry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry'),
        ),
    ]
