# Generated by Django 3.0.3 on 2020-03-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200320_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne_direct', models.BooleanField(default=True)),
                ('clé_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Airline')),
            ],
        ),
        migrations.AddField(
            model_name='airoport',
            name='ville',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plane',
            name='clé_airline',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='ligne',
            name='clé_airoportarr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airoportarr', to='blogs.Airoport'),
        ),
        migrations.AddField(
            model_name='ligne',
            name='clé_airoportdep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Airoport'),
        ),
    ]
