# Generated by Django 3.0.3 on 2020-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200323_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airoport',
            name='ville',
            field=models.CharField(max_length=200),
        ),
    ]
