# Generated by Django 3.0.3 on 2020-03-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_contry'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50)),
                ('clé_contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry')),
            ],
        ),
    ]
