# Generated by Django 3.0.3 on 2020-03-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_airline', models.CharField(max_length=200)),
                ('clé_contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry')),
            ],
        ),
        migrations.CreateModel(
            name='Airoport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_airoport', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('latitude', models.IntegerField()),
                ('timezone1', models.IntegerField()),
                ('timezone2', models.IntegerField()),
                ('clé_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.City')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plane', models.CharField(max_length=200)),
                ('code_IATA', models.CharField(max_length=20)),
                ('code_OACI', models.CharField(max_length=20)),
                ('clé_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne_direct', models.BooleanField(default=True)),
                ('clé_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Airline')),
                ('clé_airoport_arr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airoportarr', to='blogs.Airoport')),
                ('clé_airoport_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Airoport')),
            ],
        ),
    ]
