# Generated by Django 3.0.3 on 2020-03-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_airline_airoport_ligne_plane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airoport',
            name='clé_city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='clé_contry',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_airline',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_airoport_arr',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_airoport_dep',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='clé_airline',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
        migrations.DeleteModel(
            name='Airoport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Contry',
        ),
        migrations.DeleteModel(
            name='Ligne',
        ),
        migrations.DeleteModel(
            name='Plane',
        ),
    ]
