# Generated by Django 3.0.3 on 2020-03-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0010_auto_20200325_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_aeroport', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('latitude', models.IntegerField()),
                ('timezone1', models.IntegerField()),
                ('timezone2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_airline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plane', models.CharField(max_length=200)),
                ('code_IATA', models.CharField(max_length=20)),
                ('code_OACI', models.CharField(max_length=20)),
                ('clé_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne_direct', models.BooleanField(default=True)),
                ('clé_aeroport_arr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeroportarr', to='blogs.Aeroport')),
                ('clé_aeroport_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Aeroport')),
                ('clé_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Airline')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50)),
                ('clé_contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry')),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='clé_contry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Contry'),
        ),
        migrations.AddField(
            model_name='aeroport',
            name='clé_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.City'),
        ),
    ]
