# Generated by Django 3.0.3 on 2020-03-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200325_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='clé_aeroport_arr',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_aeroport_dep',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_airline',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
        migrations.DeleteModel(
            name='Ligne',
        ),
    ]
