# Generated by Django 3.0.3 on 2020-03-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20200325_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='clé_airline',
        ),
    ]
