# Generated by Django 3.0.3 on 2020-03-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20200325_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='clé_aeroport_arr',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_aeroport_dep',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_airline',
        ),
        migrations.DeleteModel(
            name='Aeroport',
        ),
        migrations.DeleteModel(
            name='Ligne',
        ),
    ]
