# Generated by Django 3.0.3 on 2020-03-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_aeroport_ligne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='clé_contry',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_aeroport_arr',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_aeroport_dep',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='clé_airline',
        ),
        migrations.DeleteModel(
            name='Aeroport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Ligne',
        ),
    ]
