# Generated by Django 3.0.3 on 2020-03-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_aeroport_ligne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ligne',
        ),
    ]
