# Generated by Django 3.0.3 on 2020-03-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_ligne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ligne',
        ),
    ]
